server:
  port: 8099
grpc:
  server:
    port: 9099
spring:
  profiles:
    active: fusion
  application:
    name: fusion
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1MB
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
      config:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        file-extension: yml



mybatis:
  type-aliases-package: com.primihub.repository
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
